// Generated by CoffeeScript 1.9.1
var dn, rr, split, up;

up = [3, 4, 5, 7, 7, 6, 6, 6, 6, 5, 5, 3, 2];

dn = [1, 2, 4, 4, 5, 5, 5, 5, 6, 6, 4, 3, 2];

split = function(hx, hy) {
  var btm, cut, dn_trim, i, j, k, l, m, qa, qb, qc, qd, ref, ref1, top, up_trim;
  top = up.slice(0);
  btm = dn.slice(0);
  if (hy < 6) {
    up_trim = 6 - hy;
  } else {
    up_trim = 0;
  }
  if (hy > 6) {
    dn_trim = hy - 6;
  } else {
    dn_trim = 0;
  }
  if (hy < 6) {
    for (j = i = 0; i <= 12; j = ++i) {
      cut = Math.min(top[j], up_trim);
      top[j] = top[j] - cut;
      btm[j] = btm[j] + cut;
    }
  }
  if (hy > 6) {
    for (j = k = 0; k <= 12; j = ++k) {
      cut = Math.min(btm[j], dn_trim);
      btm[j] = btm[j] - cut;
      top[j] = top[j] + cut;
    }
  }
  qa = 0;
  qb = 0;
  qc = 0;
  qd = 0;
  for (j = l = 0, ref = hx; 0 <= ref ? l <= ref : l >= ref; j = 0 <= ref ? ++l : --l) {
    qa += top[j];
    qc += btm[j];
  }
  for (j = m = ref1 = hx + 1; ref1 <= 12 ? m <= 12 : m >= 12; j = ref1 <= 12 ? ++m : --m) {
    qb += top[j];
    qd += btm[j];
  }
  return [qa, qb, qc, qd];
};

rr = split(9, 3);

console.log(rr[0] + "  " + rr[1] + "  " + rr[2] + "  " + rr[3]);
