// Generated by CoffeeScript 1.9.1
var a, b, c, i, rr;

for (rr = i = 0; i <= 38; rr = ++i) {
  a = rr * 3;
  b = a + 1;
  c = b + 1;
  console.log(a + " " + ((Math.floor(a * 1000 / 117)) / 1000) + "    " + b + " " + ((Math.floor(b * 1000 / 117)) / 1000) + "    " + c + " " + ((Math.floor(c * 1000 / 117)) / 1000));
}
