// Generated by CoffeeScript 1.9.1
describe("Dot drawing functions", function() {
  beforeEach(function() {
    return this.draw = new DotDraw;
  });
  return it("should find all the pixels for a dot a,b", function() {
    var dots;
    dots = this.draw.get_pixels(33, 22);
    expect(dots.length).toEqual(37);
    expect(dots).toContain([112, 52]);
    expect(dots).toContain([109, 52]);
    expect(dots).toContain([114, 54]);
    expect(dots).toContain([112, 55]);
    expect(dots).toContain([115, 53]);
    expect(dots).toContain([111, 49]);
    expect(dots).toContain([112, 49]);
    expect(dots).toContain([113, 55]);
    expect(dots).not.toContain([109, 50]);
    expect(dots).not.toContain([115, 55]);
    expect(dots).not.toContain([388, 502]);
    return expect(dots).not.toContain([400, 200]);
  });
});
