// Generated by CoffeeScript 1.9.1
describe("Dot iterator", function() {
  beforeEach(function() {
    return this.iterator = new DotIterator;
  });
  return it("should identify the first and last dot in column a", function() {
    var span;
    span = this.iterator.get_span(0);
    expect(span[0]).toEqual(15);
    expect(span[1]).toEqual(21);
    span = this.iterator.get_span(1);
    expect(span[0]).toEqual(16);
    expect(span[1]).toEqual(28);
    span = this.iterator.get_span(8);
    expect(span[0]).toEqual(15);
    expect(span[1]).toEqual(77);
    span = this.iterator.get_span(63);
    expect(span[0]).toEqual(10);
    expect(span[1]).toEqual(118);
    span = this.iterator.get_span(100);
    expect(span[0]).toEqual(7);
    expect(span[1]).toEqual(115);
    span = this.iterator.get_span(148);
    expect(span[0]).toEqual(3);
    expect(span[1]).toEqual(111);
    span = this.iterator.get_span(181);
    expect(span[0]).toEqual(78);
    expect(span[1]).toEqual(108);
    span = this.iterator.get_span(185);
    expect(span[0]).toEqual(106);
    return expect(span[1]).toEqual(108);
  });
});
