// Generated by CoffeeScript 1.9.1
describe("Square to dot conversion helpers", function() {
  beforeEach(function() {
    return this.helper = new SquareDotHelper;
  });
  return it("should find the correct starting dot column for a value of xx", function() {
    var col;
    col = this.helper.get_dot_col(8, 5);
    return expect(col).toEqual(10);
  });
});
